Repository Kubik-ERP/frontend, pull requests merged in 2025-08, with the labels that each got.

#179 Merge branch from fix/staff into 'development'
  src/app/router/index.ts
  src/modules/account/components/store-detail/AccountStoreDetailTableConfigurationDialog.vue
  src/modules/account/components/store-detail/AccountStoreTableConfiguration.vue
  src/modules/account/interfaces/account-store-detail.interface.ts
  src/modules/account/routes/account.route.ts
  src/modules/account/services/account-store-detail.service.ts
  src/modules/cashier/components/OrderSummary/Modal/CashierSummaryModalSelectTable.vue
  src/modules/catalog-product/routes/catalog-product.route.ts
  src/modules/catalog/routes/Catalog.route.ts
  src/modules/catalog/routes/customer.router.ts
  src/modules/customer-waiting-list/routes/customer-waiting-list.route.ts
  src/modules/customer/routes/customer.route.ts
  src/modules/invoice/components/InvoiceStatus.vue
  src/modules/invoice/components/paper/InvoicePaperCashierInvoice.vue
  src/modules/invoice/components/paper/InvoicePaperKitchenTicket.vue
  src/modules/invoice/components/paper/InvoicePaperTableTicket.vue
  src/modules/invoice/routes/invoice.route.ts
  src/modules/invoice/services/useInvoice.service.ts
  src/modules/purchase-order/components/PurchaseOrderListTable.vue
  src/modules/queue/routes/queue.route.ts
  src/modules/setting/components/setting-invoice/SettingInvoiceDialogInvoiceConfiguration.vue
  src/modules/setting/services/setting-invoice.service.ts
  src/modules/staff-member/components/StaffMemberWorkingHoursForm.vue
  src/modules/staff-member/constants/staff-member-create-edit.constant.ts
  src/modules/staff-member/interfaces/staff-member-create-edit.interface.ts
  src/modules/staff-member/routes/staff-member.router.ts
  src/modules/staff-member/services/staff-member-create-edit.service.ts
  src/modules/staff-member/store/index.ts
  src/style.css
Labels: bug

#191 fix(voucher): fix voucher get active voucher and disabled if minPrice > total
  src/modules/cashier/components/OrderSummary/Modal/CashierSummaryModalVoucher.vue
  src/modules/cashier/services/useCashierOrderSummary.service.ts
  src/modules/voucher/store/index.ts
Labels: bug

#193 feat(purchase-order): added ui for feature purchase order
  src/app/assets/icons/document.svg
  src/app/components/base/AppBaseDataTable.vue
  src/app/components/index.ts
  src/app/components/layouts/AppLayoutSimpleNavbar.vue
  src/app/components/layouts/index.ts
  src/app/constants/layout.constant.ts
  src/app/constants/menus.constant.ts
  src/interfaces.d.ts
  src/modules/purchase-order/components/PurchaseOrderCreateEditAddProductDialog.vue
  src/modules/purchase-order/components/PurchaseOrderCreateEditButtonActions.vue
  src/modules/purchase-order/components/PurchaseOrderCreateEditForm.vue
  src/modules/purchase-order/components/PurchaseOrderEditQuantityDialog.vue
  src/modules/purchase-order/components/PurchaseOrderListTable.vue
  src/modules/purchase-order/constants/index.ts
  src/modules/purchase-order/constants/purchase-order-api.constant.ts
  src/modules/purchase-order/constants/purchase-order-create-edit.constant.ts
  src/modules/purchase-order/constants/purchase-order.constant.ts
  src/modules/purchase-order/interfaces/index.ts
  src/modules/purchase-order/interfaces/purchase-order-create-edit.interface.ts
  src/modules/purchase-order/interfaces/purchase-order-list.interface.ts
  src/modules/purchase-order/locales/purchase-order.locale.en.json
  src/modules/purchase-order/locales/purchase-order.locale.id.json
  src/modules/purchase-order/routes/purchase-order.route.ts
  src/modules/purchase-order/services/purchase-order-create-edit.service.ts
  src/modules/purchase-order/services/purchase-order-list.service.ts
  src/modules/purchase-order/store/index.ts
  src/modules/purchase-order/views/PurchaseOrderCreateEditUI.vue
  src/modules/purchase-order/views/PurchaseOrderListUI.vue
  src/modules/staff/routes/staff.route.ts
Labels: enhancement

#211 Merge branch from 'feat/point' into 'development'
  src/app/constants/menus.constant.ts
  src/modules/catalog-product/locales/catalog-product.locale.en.json
  src/modules/customer-waiting-list/routes/customer-waiting-list.route.ts
  src/modules/customer-waiting-list/views/Customer-waiting-listUI.vue
  src/modules/customer/components/detailCustomer/loyaltyPoint.vue
  src/modules/customer/components/detailCustomer/salesInvoice.vue
  src/modules/customer/constants/customer-loyalty-point.constant.ts
  src/modules/customer/constants/customerApi.constant.ts
  src/modules/customer/interfaces/CustomerDetailInterface.ts
  src/modules/customer/interfaces/CustomersInterface.ts
  src/modules/customer/services/CustomersService.ts
  src/modules/customer/services/customer-detail.service.ts
  src/modules/customer/store/index.ts
  src/modules/customer/views/PreviewCustomerUI.vue
  src/modules/point-configuration/components/.gitkeep
  src/modules/point-configuration/components/LoyaltyPointBenefit/DialogDiscount.vue
  src/modules/point-configuration/components/LoyaltyPointBenefit/DialogFreeItems.vue
  src/modules/point-configuration/components/LoyaltyPointBenefit/DiscountFreeItems/Discount.vue
  src/modules/point-configuration/components/LoyaltyPointBenefit/DiscountFreeItems/FreeItems.vue
  src/modules/point-configuration/components/LoyaltyPointBenefit/Table.vue
  src/modules/point-configuration/constants/index.ts
  src/modules/point-configuration/constants/loyalty-point-benefit.constant.ts
  src/modules/point-configuration/constants/point-configuration-api.constant.ts
  src/modules/point-configuration/constants/point-configuration.constant.ts
  src/modules/point-configuration/interfaces/index.ts
  src/modules/point-configuration/interfaces/loyalty-point-benefit.interface.ts
  src/modules/point-configuration/interfaces/point-configuration.interface.ts
  src/modules/point-configuration/routes/point-configuration.route.ts
  src/modules/point-configuration/services/loyalty-point-benefit.service.ts
  src/modules/point-configuration/services/point-configuration.service.ts
  src/modules/point-configuration/store/index.ts
  src/modules/point-configuration/views/LoyaltyPointBenefitUI.vue
  src/modules/point-configuration/views/LoyaltyPointSettingUI.vue
  src/modules/point-configuration/views/pointConfigurationUI.vue
  src/modules/staff-member/components/StaffMemberWorkingHoursForm.vue
  src/modules/staff-member/interfaces/index.ts
  src/modules/staff-member/interfaces/staff-member-create-edit.interface.ts
  src/modules/staff-member/interfaces/staff-member-list.interface.ts
  src/modules/staff-member/services/staff-member-create-edit.service.ts
  src/modules/staff-member/store/index.ts
  src/modules/voucher/components/VoucherListTable.vue
Labels: enhancement

#235 feat(cash-in-out): do integration API on list cash in out
  src/modules/cash-drawer/interfaces/index.ts
  src/modules/cash-in-out/constants/cash-in-out-api.constant.ts
  src/modules/cash-in-out/constants/cash-in-out.constant.ts
  src/modules/cash-in-out/interfaces/cash-in-out-list.interface.ts
  src/modules/cash-in-out/interfaces/index.ts
  src/modules/cash-in-out/services/cash-in-out-list.service.ts
  src/modules/cash-in-out/services/cash-in-out.service.ts
  src/modules/cash-in-out/store/index.ts
  src/modules/cash-in-out/views/CashInOutListUI.vue
  src/modules/sales-order/services/sales-order.service.ts
Labels: enhancement

#236 feat(stock-opname): added new page of stock opname
  src/app/assets/icons/checkCircle-green.svg
  src/app/assets/icons/chevron-down-red.svg
  src/app/assets/icons/close-circle-red.svg
  src/app/assets/icons/confirmation-cancel.svg
  src/app/constants/menus.constant.ts
  src/modules/catalog-product/locales/catalog-product.locale.en.json
  src/modules/catalog-product/views/AddProductUI.vue
  src/modules/catalog-product/views/EditProductUI.vue
  src/modules/catalog/components/Category/CategoryTable.vue
  src/modules/stock-opname/components/.gitkeep
  src/modules/stock-opname/components/DialogNotes.vue
  src/modules/stock-opname/constants/index.ts
  src/modules/stock-opname/constants/stock-opname-api.constant.ts
  src/modules/stock-opname/constants/stock-opname.constant.ts
  src/modules/stock-opname/interfaces/index.ts
  src/modules/stock-opname/locales/stock-opname.locale.en.json
  src/modules/stock-opname/locales/stock-opname.locale.id.json
  src/modules/stock-opname/routes/stock-opname.route.ts
  src/modules/stock-opname/services/stock-opname.service.ts
  src/modules/stock-opname/store/index.ts
  src/modules/stock-opname/views/Stock-opnameUI.vue
  src/modules/stock-opname/views/stock-opnameCreateEditUI.vue
  src/modules/stock-opname/views/stock-opnameDetailUI.vue
Labels: enhancement

#237 feat(account): do integration API for store facilities
  src/modules/account/components/store-detail/AccountStoreFacility.vue
  src/modules/account/components/store-detail/store-facility/CreateEditDialog.vue
  src/modules/account/constants/account-api.constant.ts
  src/modules/account/interfaces/account-store-detail.interface.ts
  src/modules/account/services/account-store-detail.service.ts
  src/modules/account/store/index.ts
  src/modules/account/views/AccountStoreDetailUI.vue
Labels: enhancement

#242 feat(product-bundling): added new feature of product bundling
  src/app/constants/menus.constant.ts
  src/modules/product-bundling/components/.gitkeep
  src/modules/product-bundling/constants/index.ts
  src/modules/product-bundling/constants/product-bundling-api.constant.ts
  src/modules/product-bundling/constants/product-bundling.constant.ts
  src/modules/product-bundling/interfaces/index.ts
  src/modules/product-bundling/locales/product-bundling.locale.en.json
  src/modules/product-bundling/locales/product-bundling.locale.id.json
  src/modules/product-bundling/routes/product-bundling.route.ts
  src/modules/product-bundling/services/product-bundling.service.ts
  src/modules/product-bundling/store/index.ts
  src/modules/product-bundling/views/ProductBundlingCreateEditUI.vue
  src/modules/product-bundling/views/ProductBundlingListUI.vue
Labels: enhancement

#251 feat: adjust a lot of responsive design
  index.html
  src/App.vue
  src/app/assets/icons/menu.svg
  src/app/components/base/AppBaseBreadcrumb.vue
  src/app/components/base/AppBaseDataTable.vue
  src/app/components/base/AppBaseNavbar.vue
  src/app/components/base/AppBaseSidebar.vue
  src/app/components/base/AppBaseTabs.vue
  src/app/components/base/AppInitializationLoader.vue
  src/app/components/index.ts
  src/app/components/layouts/AppLayoutDefault.vue
  src/app/router/index.ts
  src/app/store/loading.store.ts
  src/app/store/mobile.store.ts
  src/main.ts
  src/modules/account/components/AccountBankInformation.vue
  src/modules/account/components/AccountStores.vue
  src/modules/account/components/store-detail/AccountAssignedStaff.vue
  src/modules/account/components/store-detail/AccountStoreDetailInformation.vue
  src/modules/account/components/store-detail/AccountStoreDetailTableConfigurationDialog.vue
  src/modules/account/components/store-detail/AccountStoreFacility.vue
  src/modules/account/components/store-detail/AccountStoreTableConfiguration.vue
  src/modules/account/components/store-edit/AccountStoreEditFormDetail.vue
  src/modules/account/components/table-configuration/AccountStoreTableConfigurationNotFound.vue
  src/modules/account/services/account-store-table-configuration.service.ts
  src/modules/daily-sales/views/DailySalesListUI.vue
  src/modules/dashboard/components/DashboardChartLatestSales.vue
  src/modules/dashboard/components/DashboardLowStock.vue
  src/modules/dashboard/components/DashboardOverviews.vue
  src/modules/dashboard/components/DashboardStockAvailability.vue
  src/modules/dashboard/components/DashboardTopProducts.vue
  src/modules/outlet/components/OutletAvailableList.vue
  src/modules/outlet/components/OutletCreateEditFormDetail.vue
  src/modules/outlet/components/OutletCreateEditFormLocation.vue
  src/modules/outlet/interfaces/index.ts
  src/modules/outlet/store/index.ts
  src/modules/sales-order/views/SalesOrderUI.vue
Labels: bug, enhancement
